[build]
  command = "npm run build"
  publish = "dist"
  functions = "./netlify/functions/"  

[functions]
  node_bundler = "esbuild"

# Branch deploy settings
[context.deploy-preview]
  command = "npm run build"

# Force HTTPS for all domains
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Domain aliases and HTTPS redirects
[[redirects]]
  from = "http://nztechrally.nz/2023/*"
  to = "https://2023.nztechrally.nz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://nztechrally.nz/2023/*"
  to = "https://2023.nztechrally.nz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://2023.nztechrally.nz/*"
  to = "https://2023.nztechrally.nz/:splat"
  status = 301
  force = true
