[build]
  command = "npm run build"
  publish = "dist"
  functions = "./netlify/functions/"  

[functions]
  node_bundler = "esbuild"

# Branch deploy settings
[context.deploy-preview]
  command = "npm run build"

# Force HTTPS for all domains
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Domain aliases and HTTPS redirects

# Serve assets for 2023 subdomain
[[redirects]]
  from = "https://2023.nztechrally.nz/assets/*"
  to = "/assets/:splat"
  status = 200
  force = true

# Serve crew pages for 2023 subdomain  
[[redirects]]
  from = "https://2023.nztechrally.nz/crew/*"
  to = "/crew/:splat"
  status = 200
  force = true

# Serve speakers pages for 2023 subdomain
[[redirects]]
  from = "https://2023.nztechrally.nz/speakers/*"
  to = "/2023/speakers/:splat"
  status = 200
  force = true

# Serve panellists pages for 2023 subdomain
[[redirects]]
  from = "https://2023.nztechrally.nz/panellists/*"
  to = "/2023/panellists/:splat"
  status = 200
  force = true

# Handle 2023 paths on subdomain - redirect to root
[[redirects]]
  from = "https://2023.nztechrally.nz/2023/*"
  to = "https://2023.nztechrally.nz/:splat"
  status = 301
  force = true

# Serve /2023/ content for 2023.nztechrally.nz subdomain
[[redirects]]
  from = "https://2023.nztechrally.nz/*"
  to = "/2023/:splat"
  status = 200
  force = true

# Redirect main domain /2023/ paths to subdomain
[[redirects]]
  from = "http://nztechrally.nz/2023/*"
  to = "https://2023.nztechrally.nz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://nztechrally.nz/2023/*"
  to = "https://2023.nztechrally.nz/:splat"
  status = 301
  force = true

# Force HTTPS for subdomain
[[redirects]]
  from = "http://2023.nztechrally.nz/*"
  to = "https://2023.nztechrally.nz/:splat"
  status = 301
  force = true
